version: '3.8'

services:

  db:
    image: postgres:alpine3.14
    restart: always
    volumes:
      - dbvolume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    container_name: pgdb
    env_file:
      - ./core/.env
    networks:
      djangonetwork:

  web:
    build: .
    volumes:
      # - .:/app
      - static:/static 
      - media:/media 
      # - mediavol1:/opt/services/app/media
      # - statvol:/vol/web/static
    ports:
      - "8000:8000"
    image: web:django
    container_name: django_app
    command: gunicorn core.wsgi:application workers 4 --bind 0.0.0.0:$PORT
    depends_on:
      - db
    networks:
      main:
        aliases:
          - web
      djangonetwork:


  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - 80:8080
  #   volumes:
  #     - ./config/setup.conf:/etc/nginx/conf.d/default.conf
  #     - staticvol1:/opt/services/app/static
  #     - mediavol1:/opt/services/app/media

  #   depends_on:
  #     - app
  #   networks:
  #     nginx_network:
  nginx:
    build: ./config
    volumes:
      - static:/static
      - media:/media
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      main:
        aliases:
          - nginx
  # worker:
  #   build: .
  #   command: python manage.py rqworker default
  #   environment:
  #     DEBUG: 1
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - app
      
volumes:
  dbvolume:
  static:
  media:
  # mediavol1:

networks:
  # nginx_network:
  #   driver: bridge
  main:
  djangonetwork:
    driver: bridge