# Generated by Django 3.2.6 on 2022-03-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20220312_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
