# Generated by Django 3.2.6 on 2022-03-17 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patientmodel_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChoicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='patientstatusmodel',
            name='status',
            field=models.ForeignKey(max_length=22, on_delete=django.db.models.deletion.CASCADE, to='patients.statuschoicesmodel'),
        ),
    ]
