# Generated by Django 3.2.6 on 2022-03-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Xesteliyin Adi:')),
            ],
        ),
        migrations.CreateModel(
            name='OperationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('starting_date', models.DateTimeField(auto_now_add=True)),
                ('finished_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('disease', models.ManyToManyField(related_name='disease_operations', to='disease.DiseaseModel')),
                ('doctor', models.ManyToManyField(related_name='doctor_operations', to='doctors.DoctorModel')),
            ],
        ),
    ]
