# Generated by Django 3.2.6 on 2022-03-12 13:15

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disease', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Ad:')),
                ('last_name', models.CharField(max_length=40, verbose_name='Soyadi:')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('joining_date', models.DateTimeField(auto_now_add=True, verbose_name='Giris Tarixi:')),
                ('expected_discharging_date', models.DateTimeField(blank=True, null=True, verbose_name='Gozlenilen Cixis Tarixi:')),
                ('discharged_date', models.DateTimeField(blank=True, null=True, verbose_name='Cixis Tarixi:')),
                ('born_date', models.DateField(verbose_name='Dogum Tarixi:')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('disease', models.ManyToManyField(related_name='disease_patients', to='disease.DiseaseModel')),
            ],
        ),
        migrations.CreateModel(
            name='PeopleWithPatientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_ppl_with_patient', to='doctors.doctormodel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_ppl_with_patient', to='patients.patientmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PatientStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Yaxsi', 'Yaxsi'), ('Stabil', 'Stabil'), ('Agir', 'Agir'), ('Emeliyyata_Hazirlasir', 'Emeliyyata Hazirlasir'), ('Emeliyyatdadir', 'Emeliyyatdadir')], max_length=22)),
                ('note', models.TextField(verbose_name='Xestenin cari veziyyeti haqqinda melumat:')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Gun Ve Vaxt:')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctormodel')),
                ('patient', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_status', to='patients.patientmodel')),
            ],
        ),
    ]
