# Generated by Django 3.2.6 on 2022-03-27 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0004_auto_20220317_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplewithpatientmodel',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_ppl_with_patient', to='doctors.doctormodel'),
        ),
    ]
