# Generated by Django 3.2.6 on 2022-03-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0005_alter_peoplewithpatientmodel_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peoplewithpatientmodel',
            name='doctor',
        ),
        migrations.AddField(
            model_name='peoplewithpatientmodel',
            name='doctor',
            field=models.ManyToManyField(blank=True, null=True, related_name='doctor_ppl_with_patient', to='doctors.DoctorModel'),
        ),
    ]
