# Generated by Django 3.2.6 on 2022-04-05 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_auto_20220330_1221'),
        ('patients', '0009_auto_20220330_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientstatusmodel',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctormodel'),
        ),
    ]
