# Generated by Django 3.2.6 on 2022-03-30 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_peoplewithpatientmodel_doctor'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormodel',
            name='blood_type',
            field=models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.bloodtypemodel'),
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='gender',
            field=models.ForeignKey(max_length=6, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.gendermodel'),
        ),
    ]
