# Generated by Django 3.2.6 on 2022-03-30 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_bloodtypemodel_gendermodel'),
        ('doctors', '0002_auto_20220330_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormodel',
            name='blood_type',
            field=models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.bloodtypemodel'),
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='gender',
            field=models.ForeignKey(max_length=6, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.gendermodel'),
        ),
    ]
